
DATA_DIR = 'data/'
ALL_DRIVERS_PATH = DATA_DIR + 'all_drivers.txt'
CONFIG_PATH = DATA_DIR + 'config.json'
DESIGN_PATH = DATA_DIR + 'design.json'
LINKS_PATH = DATA_DIR + 'links.json'
LOGS_PATH = DATA_DIR + 'logs.txt'
MONTHLY_HOURS_FUND_PATH = DATA_DIR + 'monthly_hours_fund.json'

CENTRAL_DATA_DIR = DATA_DIR + 'central_data/'
NOTIFICATIONS_FILES_DIR = CENTRAL_DATA_DIR + 'notifications_files/'
UPDATE_INFO_FILE = 'update_info.json'
WEEK_SERVICES_BY_DRIVER_ENCRYPTED_PDF_FILE = 'tpd.pdf'
UPDATE_INFO_PATH = CENTRAL_DATA_DIR + UPDATE_INFO_FILE
COMPRESSED_SERVICES_PATH = CENTRAL_DATA_DIR + 'services.zip'
COMPRESSED_SHIFTS_PATH = CENTRAL_DATA_DIR + 'shifts.zip'
COMPRESSED_UPDATED_SERVICES_PATH = CENTRAL_DATA_DIR + 'updated_services.zip'
COMPRESSED_UPDATED_SHIFTS_PATH = CENTRAL_DATA_DIR + 'updated_shifts.zip'
WEEK_SERVICES_BY_DRIVER_ENCRYPTED_PATH = CENTRAL_DATA_DIR + 'week_services_by_driver_encrypted.txt'
WEEK_SERVICES_BY_DRIVER_ENCRYPTED_PDF_PATH = CENTRAL_DATA_DIR + WEEK_SERVICES_BY_DRIVER_ENCRYPTED_PDF_FILE
HOLIDAYS_PATH = CENTRAL_DATA_DIR + 'holidays.txt'
NOTIFICATIONS_PATH = CENTRAL_DATA_DIR + 'notifications.json'
STATISTICS_PATH = CENTRAL_DATA_DIR +'statistics.json'
WARNINGS_PATH = CENTRAL_DATA_DIR + 'warnings.txt'
PRIMARY_WORK_DAY_RULES_FILE_PREFIX = 'rules_W'
PRIMARY_WORK_DAY_RULES_PATH = CENTRAL_DATA_DIR + PRIMARY_WORK_DAY_RULES_FILE_PREFIX + '.txt'
PRIMARY_SATURDAY_RULES_FILE_PREFIX = 'rules_ST'
PRIMARY_SATURDAY_RULES_PATH = CENTRAL_DATA_DIR + PRIMARY_SATURDAY_RULES_FILE_PREFIX + '.txt'
PRIMARY_SUNDAY_RULES_FILE_PREFIX = 'rules_SN'
PRIMARY_SUNDAY_RULES_FILE_PATH = CENTRAL_DATA_DIR + PRIMARY_SUNDAY_RULES_FILE_PREFIX + '.txt'
PRIMARY_SPECIAL_RULES_FILE_PREFIX = 'rules_SP'

DOWNLOAD_DATA_DIR = DATA_DIR + 'download/'
DOWNLOADED_CENTRAL_DATA_FILE = 'central_data.zip'
DOWNLOADED_CENTRAL_DATA_PATH = DOWNLOAD_DATA_DIR + DOWNLOADED_CENTRAL_DATA_FILE
DOWNLOADED_UPDATE_INFO_PATH = DOWNLOAD_DATA_DIR + UPDATE_INFO_FILE

UPLOAD_DATA_DIR = DATA_DIR + 'upload/'
UPLOADED_CENTRAL_DATA_FILE = 'central_data.zip'
UPLOADED_CENTRAL_DATA_PATH_NO_EXT = UPLOAD_DATA_DIR + 'central_data'
UPLOADED_CENTRAL_DATA_PATH = UPLOADED_CENTRAL_DATA_PATH_NO_EXT + '.zip'
UPLOADED_UPDATE_INFO_PATH = UPLOAD_DATA_DIR + UPDATE_INFO_FILE