#:include design/screen/main/tabs/services/services_tab.kv
#:include design/screen/main/tabs/shifts/shifts_tab.kv
#:include design/screen/main/tabs/hourly_rate/hourly_rate_tab.kv

<MainScreen>:
	name: 'mainScreen'
	#mainScreenTabs: mainScreenTabsId
	#servicesTab: servicesTabId
	#shiftsTab: shiftsTabId
	#hourlyRateTab: hourlyRateTabId

	MDBoxLayout:
		orientation: 'vertical'
		
		#MDTopAppBar:
		#	orientation: 'horizontal'
		#	title: 'ZETSluzbe'

		
		
				
			